### ISSUE TITLE
-Os switch to gcc causes compilation warning and hence error

### ISSUE THREAD

**Issue by spe-ciellt** [kelvinlawson/atomthreads#12]
Hello!

I turned on the -Os switch to gcc in my Arduino Nano port and that generated a compilation warning and (by the nature of -Werror) an error.
The fix is silly simple,  please see my fork at https://github.com/spe-ciellt/atomthreads and particulary the commit https://github.com/spe-ciellt/atomthreads/commit/16cfe63fa003bd188c1639f0c17f3acde7ff3aae

Thanks  and best regards,
/Stefan

**Comment by kelvinlawson** [comment]
Thanks for the report, it looks like it's just the "callback_list_tail" that it complained about so I've initialised that one to NULL. This compiles with -Os with the version of avr-gcc that I'm using. Thanks.
