### ISSUE TITLE
atomTimerDelay 

### ISSUE THREAD

**Issue by AlexRebega** [kelvinlawson/atomthreads#27]
In atomTimerDelay pass the address of a local variable(  ATOM_TIMER timer_cb ) to another function:

atomTimerRegister (&timer_cb).  

This is clearly a mistake and, as a result, in my program it only puts the idle_thread in the readyQueue. I come with a fix in a few days...

**Comment by tidklaas** [comment]
No, this is perfectly okay. The timer_cb is located on the calling thread's attack. After successfully registering the timer_cb, the thread is suspended and scheduled out by the call to atomSched(). This means that its stack will not be altered until it is scheduled back in, therefore the reference is valid until this happens.
As for the idle thread, that is what is supposed to happen. You just suspended your thread. Unless there are any other threads ready to run, the idle thread will be scheduled in and run until a higher priority thread gets woken up.
