### ISSUE TITLE
Address of local variable timer_cb is assigned to a non-local variable

### ISSUE THREAD

**Issue by szsam** [kelvinlawson/atomthreads#37]
Storing the address of a local variable in non-local memory can cause a dangling pointer bug if the address is used after the function returns.
https://github.com/kelvinlawson/atomthreads/blob/1a2f9bae753b5ed171bbbde94a97d8484a7bca55/kernel/atomtimer.c#L372
https://github.com/kelvinlawson/atomthreads/blob/1a2f9bae753b5ed171bbbde94a97d8484a7bca55/kernel/atomsem.c#L380
https://github.com/kelvinlawson/atomthreads/blob/1a2f9bae753b5ed171bbbde94a97d8484a7bca55/kernel/atomqueue.c#L399
https://github.com/kelvinlawson/atomthreads/blob/1a2f9bae753b5ed171bbbde94a97d8484a7bca55/kernel/atommutex.c#L415
https://github.com/kelvinlawson/atomthreads/blob/1a2f9bae753b5ed171bbbde94a97d8484a7bca55/kernel/atomqueue.c#L607

**Comment by tidklaas** [comment]
The timer_cb is created on the stack of the calling task, which is about to get suspended. If the timer callback occurs, the task's execution is still suspended at the atomSched() call, so the local variables on the stack are still valid.
If the task is resumed before the callback occurs, the timer gets deleted before it executes, so this is also not a problem.

**Comment by szsam** [comment]
Thanks for your explanation!
